//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MOdelClass", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class MOdelClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITestService")]
    public interface ITestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/DoWork", ReplyAction="http://tempuri.org/ITestService/DoWorkResponse")]
        System.Data.DataSet DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/DoWork", ReplyAction="http://tempuri.org/ITestService/DoWorkResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/SaveBookInfo", ReplyAction="http://tempuri.org/ITestService/SaveBookInfoResponse")]
        void SaveBookInfo(System.Data.DataSet dss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/SaveBookInfo", ReplyAction="http://tempuri.org/ITestService/SaveBookInfoResponse")]
        System.Threading.Tasks.Task SaveBookInfoAsync(System.Data.DataSet dss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/GetBookInfo", ReplyAction="http://tempuri.org/ITestService/GetBookInfoResponse")]
        System.Data.DataSet GetBookInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/GetBookInfo", ReplyAction="http://tempuri.org/ITestService/GetBookInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetBookInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/Test", ReplyAction="http://tempuri.org/ITestService/TestResponse")]
        void Test(BookStore.ServiceReference1.MOdelClass md);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/Test", ReplyAction="http://tempuri.org/ITestService/TestResponse")]
        System.Threading.Tasks.Task TestAsync(BookStore.ServiceReference1.MOdelClass md);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/Test1", ReplyAction="http://tempuri.org/ITestService/Test1Response")]
        void Test1(string name, string auth, int price, byte[] img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/Test1", ReplyAction="http://tempuri.org/ITestService/Test1Response")]
        System.Threading.Tasks.Task Test1Async(string name, string auth, int price, byte[] img);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestServiceChannel : BookStore.ServiceReference1.ITestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestServiceClient : System.ServiceModel.ClientBase<BookStore.ServiceReference1.ITestService>, BookStore.ServiceReference1.ITestService {
        
        public TestServiceClient() {
        }
        
        public TestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public void SaveBookInfo(System.Data.DataSet dss) {
            base.Channel.SaveBookInfo(dss);
        }
        
        public System.Threading.Tasks.Task SaveBookInfoAsync(System.Data.DataSet dss) {
            return base.Channel.SaveBookInfoAsync(dss);
        }
        
        public System.Data.DataSet GetBookInfo() {
            return base.Channel.GetBookInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetBookInfoAsync() {
            return base.Channel.GetBookInfoAsync();
        }
        
        public void Test(BookStore.ServiceReference1.MOdelClass md) {
            base.Channel.Test(md);
        }
        
        public System.Threading.Tasks.Task TestAsync(BookStore.ServiceReference1.MOdelClass md) {
            return base.Channel.TestAsync(md);
        }
        
        public void Test1(string name, string auth, int price, byte[] img) {
            base.Channel.Test1(name, auth, price, img);
        }
        
        public System.Threading.Tasks.Task Test1Async(string name, string auth, int price, byte[] img) {
            return base.Channel.Test1Async(name, auth, price, img);
        }
    }
}
